from typing import Protocol
from uuid import UUID

from agentctl.domain import (
    Binding,
    Conflict,
    Extension,
    PrecedenceChain,
    Project,
    Source,
)


class ExtensionRepository(Protocol):
    def create(self, extension: Extension) -> None: ...
    def get(self, extension_id: UUID) -> Extension | None: ...
    def list(self) -> list[Extension]: ...
    def update(self, extension: Extension) -> None: ...
    def delete(self, extension_id: UUID) -> None: ...


class BindingRepository(Protocol):
    def create(self, binding: Binding) -> None: ...
    def get(self, binding_id: UUID) -> Binding | None: ...
    def list_for_extension(self, extension_id: UUID) -> list[Binding]: ...
    def list(self) -> list[Binding]: ...
    def update(self, binding: Binding) -> None: ...
    def delete(self, binding_id: UUID) -> None: ...


class ConflictRepository(Protocol):
    def create(self, conflict: Conflict) -> None: ...
    def get(self, conflict_id: UUID) -> Conflict | None: ...
    def list(self) -> list[Conflict]: ...
    def update(self, conflict: Conflict) -> None: ...
    def delete(self, conflict_id: UUID) -> None: ...


class ProjectRepository(Protocol):
    def create(self, project: Project) -> None: ...
    def get(self, project_id: UUID) -> Project | None: ...
    def list(self) -> list[Project]: ...
    def update(self, project: Project) -> None: ...
    def delete(self, project_id: UUID) -> None: ...


class PrecedenceChainRepository(Protocol):
    """Keyed by (source, project_id), not by an id — PrecedenceChain has none.

    A cache of the last-computed chain (SPECS.md §9): callers must still
    treat a scan as the source of truth for display and never present a
    cached row here as current.
    """

    def upsert(self, chain: PrecedenceChain) -> None: ...
    def get(self, source: Source, project_id: UUID | None) -> PrecedenceChain | None: ...
    def list(self) -> list[PrecedenceChain]: ...
    def delete(self, source: Source, project_id: UUID | None) -> None: ...
